page_number_align: 居中
footer_distance: 2.5
line_spacing: 28
line_spacing_mode: 固定值(磅)
margin_top: 2.6
margin_bottom: 2.2
margin_left: 2.5
margin_right: 2.5
title_font: 方正小标宋简体
h1_font: 黑体
h2_font: 黑体
h3_font: 黑体
h4_font: 楷体_GB2312
h5_font: 楷体_GB2312
h6_font: 宋体
h7_font: 宋体
h8_font: 宋体
body_font: 仿宋_GB2312
page_number_font: 宋体
table_caption_font: 宋体
figure_caption_font: 宋体
attachment_font: 黑体
subtitle_font: 楷体_GB2312
table_font: 仿宋_GB2312
table_header_font: 仿宋_GB2312
english_font: Times New Roman
title_size: 22
h1_size: 16
h2_size: 15
h3_size: 15
h4_size: 14
h5_size: 12
h6_size: 10.5
h7_size: 10.5
h8_size: 10.5
body_size: 12
page_number_size: 14
table_caption_size: 10.5
figure_caption_size: 10.5
attachment_size: 16
subtitle_size: 16
table_size: 12
title_line_spacing: 33
subtitle_line_spacing: 33
heading_color: '000000'
h1_bold: true
h2_bold: true
h3_bold: true
h4_bold: true
h5_bold: true
h6_bold: true
h7_bold: false
h8_bold: false
h1_space_before: 12
h1_space_after: 12
h2_space_before: 6
h2_space_after: 6
h3_space_before: 6
h3_space_after: 6
h4_space_before: 2.4
h4_space_after: 2.4
h5_space_before: 1.2
h5_space_after: 1.2
left_indent_cm: 0.0
right_indent_cm: 0.0
set_outline: true
enable_attachment_formatting: true
force_a4: true
use_custom_english_font: true
normalize_punctuation: true
enable_table_formatting: true
table_auto_col_width: true
table_width_percent: 100
table_header_bold: true
table_smart_align: true
table_unified_borders: true
table_border_size_pt: 0.5
table_row_height_cm: 0.7
table_line_spacing: 22
heading_number_format: decimal
bold_before_colon: false
indent_h4: 360
indent_h5: 480
